### ISSUE TITLE
[코드리뷰]

### ISSUE THREAD

**Issue by booungi** [haedawn/AboutMe#1]
우선 자기소개 페이지 잘봤습니다 😄 공들인 티가 나네요! 하지만 제가 할일은 칭찬보다는 부족하거나 아쉬운 부분을 말해주는거겠죠? 

아마 다음 과제부터는 `Django` 중심일거라 `js` 가 나오기 전까지 리뷰는 없을 것 같아요..!
그래서 최대한 지금 이해 못하더라도 이후에 학습에 도움이 되도록 최대한 짚어줄게요! 천천히 공부하면서 채워가시면 좋을 것 같아요.

### 1. `image alignment` 

의도하신건지 모르겠는데 정렬이 조금 어색한감이 있네요! 의도하지 않았다면 이미지 같은 경우에는 정렬하는 방식을 최대한 레퍼런스를 참고하고 학습하면 될 것 같습니다.

![image](https://user-images.githubusercontent.com/127881256/226668617-b96eb0ae-2b73-46fb-a8cc-15838a4f9848.png)

### 2. css

- `background` property 가 두개가 선언되어있네요? 하나의 property로 줄일 수 있는 방법은 없을까요?

```css
body {
  border: rgb(75, 75, 1) 5px solid;
  background: rgb(238, 174, 202);
  background: radial-gradient(
    circle,
    rgba(238, 174, 202, 1) 0%,
    rgba(148, 187, 233, 1) 100%
  );
}
```

- `color: olive` 보통 퍼블리셔 분들이나 프론트엔드 개발자분들은 color property 를 어떤 방식으로 선언할까요? `olive` 로 선언하면 어떤 문제나 어려움이 생길까요?

```css
h1 {
  margin-top: 0px;
  border-top: 40px solid;
  background-color: beige;
  color: olive;
  font-weight: bold;
  font-size: 64px;
  font-family: Helvetica;
  text-align: center;
  border-bottom: 3px olive solid;
}
```

- 개발시에는 `통일성` 이 매우 중요하답니다! 혼자하는 경우도 있겠지만 미래에는 아마 협업을 주로 하게될테니까요! css 선언간 개행이 잘 되어있는 부분도 있지만 몇몇 부분에는 개행처리가 되어있지 않네요.

```css
.background-header {
  background-color: rgb(255, 200, 180);
  border-top: rgb(255, 162, 129) solid 3px;
  color: olive;
}
h3 {
  background-color: rgba(255, 255, 216, 50%);
  padding: 30px;
  text-align: center;
  color: rgb(75, 75, 1);
  text-transform: uppercase;
  border-top: olive solid 3px;
  border-bottom: olive solid 3px;
}
```

- 정확히 정해진 사항은 없지만 어느정도  property 선언에도 순서가 있다면 좋답니다! `css property order convention` 학습 추천드립니다.

- 또한 `html` 상에서 대문자를 사용하지 않고 css 에서 `text-transform: uppercase;` 를 사용하신 이유가 있을까요? 의도성이 없다면 어느 방식이 더욱 협업 관계에서 개발자들의 가시성에 도움이 될까요?

```css
h3 {
  background-color: rgba(255, 255, 216, 50%);
  padding: 30px;
  text-align: center;
  color: rgb(75, 75, 1);
  text-transform: uppercase;
  border-top: olive solid 3px;
  border-bottom: olive solid 3px;
}
```

- 적용되지 않은(필요없는) property들이 보이네요..! 이런 부분은 의도치 않은 결과가 생겼을 때 디버깅 하는 과정에서 큰 장애를 유발할 수 있습니다.

```css

.post-img {
  border-radius: 50rem;
  border: 0.5rem double olive;
  background-image: ;
}
```

- 퀴즈! html tag에 `className` 을 선언 후 스타일을 적용하는 방식과 지금 하신 tag 자체에 style 을 적용하는 방식은 어떻게 다를까요? 

힌트: 만일 동료 개발자가 다른 파트에서 h1 태그를 사용하고 싶을 때 정민님의 스타일이 적용되지 않을까요?

- 생각보다 같은 값을 가지고 있지만 반복적으로 적용되는 스타일 property 들이 꽤나 보이네요! `css 상수화` 학습 추천드립니다.

### 3. structure

- 이미지들이 root directory 에 중구난방으로 흩어져 있네요! 동료 개발자와의 협업을 생각한다면 구조를 어떻게 바꾸면 좋을까요?

-파일명에 한글이 들어가거나 공백이 있는 경우는 버그를 야기할 수 있습니다.

- 사용하는 이미지 확장자가 꽤나 많네요? 퍼블리셔나 프론트엔드 개발자들이 주로 사용하는 확장자는 무엇이 있을까요? 각각의 장단점이 무엇일까요? 또한, 통일성을 고려해봐도 좋지 않을까요?

### 4. html

- html markup 에는 개행이 있어도 좋습니다! 허나 의미없는 개행 혹은 의도하지 않은 개행이 있다면 오히려 가독성을 해치는 원인이 된다고 생각해요.

- inline 으로 style을 정의하면 어떤 문제가 생길 수 있을까요?

```html
          <img
            class="post-img"
            src="./profile.jpg"
            alt="my-profile"
            width="300"
            height="300"
          />
```

- `ul` 태그 내부에 `p` 태그의 `closing tag` 가 있는 모습이 부자연스러워 보이네요.

```html
            <ul>
          </p>
          <li>Birth: 2000.05.29</li>
          <li>My MBTI: INFP</li>
          <li>blood type: B</li>
          <li>phone number:010-9238-1477</li>
          <li>e-mail:haedawning@gmail.com</li>
        </ul>
```

- `main` 태그로 감싸는건 어떨까요?

```html

        <p>저의 이름은 🐨양정민 입니다.
          <br/>
          저는 국민대학교 영어영문학부에 재학중입니다.
        </p>

        <p>저의 취미는 🎨그림그리기와 🎬영화보기 입니다.</p>
```

- 이미지간의 공간을 위해 `br` 태그를 사용하는 방식은 `sementic markup` 룰에 위배되지 않을까요?

```html
        <h4>my artwork</h4>
          <img src="greatgrape.jpg" alt="grape-illustration" width="300" height="300"/>
          <img src="artwork hand.JPG" alt="hand-illustration" width="300" height="300"/>
          <img src="taeyeon.JPG" alt="taeyeon-fanart" width="300" height="300"/>
          <br/>
```

- `id` 가 대문자로 시작하는 코드는 의도적인 코드였을까요?

```html
        <p id="Copyright" class="copyright-text">
          Copyright &copy; 2023 by Haedawn
        </p>
```

### 첨언

아무래도 이후 공식적인(?) 코드리뷰는 없을 수도 있어서 학습한 기간에 비해 더 힘차게 피드백을 해봤어요! 이부분만은 꼭 지켜줬으면 하는 부분은 코드를 짜면서 계속 의도적으로 다른 코드들과 `통일성` 이 존재하는지, 깔끔한지(가시성이 좋은지), 동료 개발자들이 코드의 흐름을 쉽게 읽을 수 있는지, 반복되는 부분을 리팩토링을 통해 제거할 수 있는지 등을 생각하며 코드를 짜면 훨씬 성장이 빠를 것이라 생각합니다.

또한 제가 피드백을 드린 부분들이 주변에 물어본다면 아마 더욱 쉽게 빠르게 해결할수도 있어요. 하지만 시작이니만큼 충분한 시간을 들여 혼자 생각하고 구글링을 하며 깊이 알아가는건 어떨까요? 

너무 고생하셨고, 제가 피드백 드린 부분들은 답을 찾아 정리하셔도 되고 답글로 달아주셔도 됩니다. 또한 추가적인 질문들도 언제나 환영입니다! 🦉
